---
Name: username-auth
After:
    - "framework/*"
---

SilverStripe\Security\Member:
    extensions:
        - UsernameMemberExtension
    unique_identifier_field: Username

---
Name: MyAuth
After:
  - '#coresecurity'
---
SilverStripe\Core\Injector\Injector:
  SilverStripe\Security\Security:
    properties:
      Authenticators:
        default: %$UsernameMemberAuthenticator